### ISSUE TITLE
New Plant Application - Data Fields Required - (Aurizon Examples) Discussion

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard#351]
New Plant Application: (Discussion Topic)

Problem here is that suppliers can input '0' for fields like GVM, Tare, Height, Width etc and the Application goes through to be review stage to the Clients. See example below where they have put "0". This Application will fail when reviewed by Client. Goal here is to better the application process so I/Aurizon don't have to spend time chasing people for plant details that should be correct from the start. 

We need to look at either "0" fields being an alert in the application before they can submit or tool tips/pop-ups to say they must put in the correct details here. Tool Tip for example: could be to go to the manufacturers website, get the make & model and get the exact specs from there... (if they can't find it on their own records and manuals)

![application plant details](https://user-images.githubusercontent.com/25288888/27774653-4884212c-5fd9-11e7-9202-2797dbd04af4.png)

**Comment by jpike88** [comment]
Closed, issue streaka/plantguard#350 will resolve 0 value issue
